services:
  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: php
    ports:
      - "8080:8080"
    command: php -S 0.0.0.0:8080 -t /app/public
    volumes:
      - .:/app
